/**
 * Stat 统计指标组件属性配置
 */
import { registerSchema, type Field } from '@/components/siderBar/properties/schema/types'

const styleSchema: Field[] = [
  {
    key: 'backgroundColor',
    label: '背景颜色',
    type: 'color',
    default: '#fff',
  },
  {
    key: 'borderColor',
    label: '边框颜色',
    type: 'color',
    default: '#e0e0e0',
  },
  {
    key: 'borderWidth',
    label: '边框宽度(px)',
    type: 'number',
    min: 0,
    max: 10,
    step: 1,
    default: 1,
  },
  {
    key: 'borderRadius',
    label: '边框圆角(px)',
    type: 'number',
    min: 0,
    max: 50,
    step: 1,
    default: 8,
  },
  {
    key: 'boxShadow',
    label: '阴影',
    type: 'text',
    placeholder: '0 2px 4px rgba(0, 0, 0, 0.1)',
    default: '0 2px 4px rgba(0, 0, 0, 0.1)',
  },
  {
    key: 'padding',
    label: '内边距(px)',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    default: 20,
  },
  {
    key: 'titleColor',
    label: '标题颜色',
    type: 'color',
    default: '#333',
  },
  {
    key: 'valueColor',
    label: '数值颜色',
    type: 'color',
    default: '#3f8600',
  },
  {
    key: 'changeColorPositive',
    label: '增长颜色',
    type: 'color',
    default: '#28a745',
  },
  {
    key: 'changeColorNegative',
    label: '下降颜色',
    type: 'color',
    default: '#dc3545',
  },
  {
    key: 'titleFontSize',
    label: '标题字体大小(px)',
    type: 'number',
    min: 8,
    max: 100,
    step: 1,
    default: 14,
  },
  {
    key: 'valueFontSize',
    label: '数值字体大小(px)',
    type: 'number',
    min: 8,
    max: 200,
    step: 1,
    default: 24,
  },
  {
    key: 'changeFontSize',
    label: '变化字体大小(px)',
    type: 'number',
    min: 8,
    max: 100,
    step: 1,
    default: 14,
  },
  {
    key: 'titleFontWeight',
    label: '标题字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
      { label: '更细', value: 'lighter' },
      { label: '更粗', value: 'bolder' },
    ],
    default: 'normal',
  },
  {
    key: 'valueFontWeight',
    label: '数值字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
      { label: '更细', value: 'lighter' },
      { label: '更粗', value: 'bolder' },
    ],
    default: 'bold',
  },
  {
    key: 'changeFontWeight',
    label: '变化字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
      { label: '更细', value: 'lighter' },
      { label: '更粗', value: 'bolder' },
    ],
    default: 'normal',
  },
]

const dataSourceSchema: Field[] = [
  {
    key: 'enabled',
    label: '启用数据源',
    type: 'switch',
    default: false,
  },
  {
    key: 'url',
    label: 'API 地址',
    type: 'text',
    placeholder: 'http://localhost:3001/api/stat',
    default: '',
  },
  {
    key: 'method',
    label: '请求方法',
    type: 'select',
    options: [
      { label: 'GET', value: 'GET' },
      { label: 'POST', value: 'POST' },
    ],
    default: 'GET',
  },
  {
    key: 'interval',
    label: '自动刷新(秒)',
    type: 'number',
    min: 0,
    max: 3600,
    step: 1,
    default: 0,
  },
  {
    key: 'dataPath',
    label: '数据根路径',
    type: 'text',
    placeholder: '例: data',
    default: '',
  },
  {
    key: 'titlePath',
    label: '标题路径',
    type: 'text',
    placeholder: '例: data.title',
    default: '',
  },
  {
    key: 'valuePath',
    label: '数值路径',
    type: 'text',
    placeholder: '例: data.value',
    default: '',
  },
  {
    key: 'changePath',
    label: '变化路径',
    type: 'text',
    placeholder: '例: data.change',
    default: '',
  },
  {
    key: 'headers',
    label: '请求头(JSON)',
    type: 'text',
    placeholder: '{"Authorization": "Bearer token"}',
    default: '',
  },
]

const componentSchema: Field[] = [
  {
    key: 'title',
    label: '标题',
    type: 'text',
    placeholder: '指标标题',
    default: '指标标题',
  },
  {
    key: 'value',
    label: '数值',
    type: 'number',
    min: 0,
    step: 1,
    default: 0,
  },
  {
    key: 'icon',
    label: '图标类名',
    type: 'text',
    placeholder: 'el-icon-star-on',
    default: 'el-icon-star-on',
  },
  {
    key: 'change',
    label: '变化百分比',
    type: 'number',
    step: 0.1,
    default: 0,
  },
  {
    key: 'precision',
    label: '小数位数',
    type: 'number',
    min: 0,
    max: 10,
    step: 1,
    default: 0,
  },
  {
    key: 'suffix',
    label: '后缀',
    type: 'text',
    placeholder: '% 或 元',
    default: '',
  },
]

registerSchema({
  types: ['stat'],
  styleSchema,
  dataSourceSchema,
  componentSchema,
})
