/**
 * CountUp 数字动画组件属性配置
 */
import { registerSchema, type Field } from '@/components/siderBar/properties/schema/types'

const styleSchema: Field[] = [
  {
    key: 'backgroundColor',
    label: '背景颜色',
    type: 'color',
    default: 'transparent',
  },
  {
    key: 'borderColor',
    label: '边框颜色',
    type: 'color',
    default: 'transparent',
  },
  {
    key: 'borderWidth',
    label: '边框宽度(px)',
    type: 'number',
    min: 0,
    max: 10,
    step: 1,
    default: 0,
  },
  {
    key: 'borderRadius',
    label: '边框圆角(px)',
    type: 'number',
    min: 0,
    max: 50,
    step: 1,
    default: 0,
  },
  {
    key: 'padding',
    label: '内边距(px)',
    type: 'number',
    min: 0,
    max: 100,
    step: 1,
    default: 10,
  },
  {
    key: 'align',
    label: '对齐方式',
    type: 'select',
    options: [
      { label: '左对齐', value: 'flex-start' },
      { label: '居中', value: 'center' },
      { label: '右对齐', value: 'flex-end' },
    ],
    default: 'center',
  },
  {
    key: 'valueColor',
    label: '数值颜色',
    type: 'color',
    default: '#303133',
  },
  {
    key: 'valueFontSize',
    label: '数值字体大小(px)',
    type: 'number',
    min: 12,
    max: 200,
    step: 1,
    default: 32,
  },
  {
    key: 'valueFontWeight',
    label: '数值字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
      { label: '更细', value: 'lighter' },
      { label: '更粗', value: 'bolder' },
    ],
    default: 'bold',
  },
  {
    key: 'prefixColor',
    label: '前缀颜色',
    type: 'color',
    default: '#909399',
  },
  {
    key: 'prefixFontSize',
    label: '前缀字体大小(px)',
    type: 'number',
    min: 8,
    max: 100,
    step: 1,
    default: 16,
  },
  {
    key: 'prefixFontWeight',
    label: '前缀字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
    ],
    default: 'normal',
  },
  {
    key: 'suffixColor',
    label: '后缀颜色',
    type: 'color',
    default: '#909399',
  },
  {
    key: 'suffixFontSize',
    label: '后缀字体大小(px)',
    type: 'number',
    min: 8,
    max: 100,
    step: 1,
    default: 16,
  },
  {
    key: 'suffixFontWeight',
    label: '后缀字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
    ],
    default: 'normal',
  },
  {
    key: 'fontFamily',
    label: '字体',
    type: 'text',
    placeholder: 'inherit',
    default: 'inherit',
  },
  {
    key: 'titleColor',
    label: '标题颜色',
    type: 'color',
    default: '#909399',
  },
  {
    key: 'titleFontSize',
    label: '标题字体大小(px)',
    type: 'number',
    min: 8,
    max: 100,
    step: 1,
    default: 14,
  },
  {
    key: 'titleFontWeight',
    label: '标题字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
    ],
    default: 'normal',
  },
]

const dataSourceSchema: Field[] = [
  {
    key: 'enabled',
    label: '启用数据源',
    type: 'switch',
    default: false,
  },
  {
    key: 'url',
    label: 'API 地址',
    type: 'text',
    placeholder: 'http://localhost:3001/api/countup',
    default: '',
  },
  {
    key: 'method',
    label: '请求方法',
    type: 'select',
    options: [
      { label: 'GET', value: 'GET' },
      { label: 'POST', value: 'POST' },
    ],
    default: 'GET',
  },
  {
    key: 'interval',
    label: '自动刷新(秒)',
    type: 'number',
    min: 0,
    max: 3600,
    step: 1,
    default: 0,
  },
  {
    key: 'dataPath',
    label: '数据根路径',
    type: 'text',
    placeholder: '例: data',
    default: '',
  },
  {
    key: 'titlePath',
    label: '标题路径',
    type: 'text',
    placeholder: '例: title 或 data.title',
    default: '',
  },
  {
    key: 'valuePath',
    label: '数值路径',
    type: 'text',
    placeholder: '例: value 或 data.value',
    default: '',
  },
  {
    key: 'headers',
    label: '请求头(JSON)',
    type: 'text',
    placeholder: '{"Authorization": "Bearer token"}',
    default: '',
  },
]

const componentSchema: Field[] = [
  {
    key: 'title',
    label: '标题',
    type: 'text',
    placeholder: '总销售额',
    default: '',
  },
  {
    key: 'value',
    label: '目标数值',
    type: 'number',
    step: 0.01,
    default: 0,
  },
  {
    key: 'startValue',
    label: '起始数值',
    type: 'number',
    step: 0.01,
    default: 0,
  },
  {
    key: 'duration',
    label: '动画时长(毫秒)',
    type: 'number',
    min: 0,
    max: 10000,
    step: 100,
    default: 2000,
  },
  {
    key: 'decimals',
    label: '小数位数',
    type: 'number',
    min: 0,
    max: 10,
    step: 1,
    default: 0,
  },
  {
    key: 'separator',
    label: '千分位分隔符',
    type: 'text',
    placeholder: ',',
    default: ',',
  },
  {
    key: 'prefix',
    label: '前缀',
    type: 'text',
    placeholder: '¥',
    default: '',
  },
  {
    key: 'suffix',
    label: '后缀',
    type: 'text',
    placeholder: '元',
    default: '',
  },
  {
    key: 'showPrefix',
    label: '显示前缀',
    type: 'switch',
    default: true,
  },
  {
    key: 'showSuffix',
    label: '显示后缀',
    type: 'switch',
    default: true,
  },
  {
    key: 'customPrefix',
    label: '自定义前缀样式',
    type: 'switch',
    default: false,
  },
  {
    key: 'customSuffix',
    label: '自定义后缀样式',
    type: 'switch',
    default: false,
  },
  {
    key: 'useEasing',
    label: '使用缓动效果',
    type: 'switch',
    default: true,
  },
]

registerSchema({
  types: ['countUp'],
  styleSchema,
  dataSourceSchema,
  componentSchema,
})
