/**
 * Badge 徽章组件属性配置
 */
import { registerSchema, type Field } from '@lowcode/editor/components/siderBar/properties/schema/types'

const styleSchema: Field[] = [
  {
    key: 'padding',
    label: '外边距(px)',
    type: 'number',
    min: 0,
    max: 20,
    step: 1,
    default: 4,
  },
  {
    key: 'backgroundColor',
    label: '背景颜色',
    type: 'color',
    default: '#409eff',
  },
  {
    key: 'successColor',
    label: '成功类型颜色',
    type: 'color',
    default: '#67c23a',
  },
  {
    key: 'warningColor',
    label: '警告类型颜色',
    type: 'color',
    default: '#e6a23c',
  },
  {
    key: 'dangerColor',
    label: '危险类型颜色',
    type: 'color',
    default: '#f56c6c',
  },
  {
    key: 'infoColor',
    label: '信息类型颜色',
    type: 'color',
    default: '#909399',
  },
  {
    key: 'textColor',
    label: '文字颜色',
    type: 'color',
    default: '#fff',
  },
  {
    key: 'fontSize',
    label: '字体大小(px)',
    type: 'number',
    min: 8,
    max: 50,
    step: 1,
    default: 12,
  },
  {
    key: 'fontWeight',
    label: '字重',
    type: 'select',
    options: [
      { label: '常规', value: 'normal' },
      { label: '加粗', value: 'bold' },
    ],
    default: 'bold',
  },
  {
    key: 'paddingX',
    label: '水平内边距(px)',
    type: 'number',
    min: 0,
    max: 30,
    step: 1,
    default: 6,
  },
  {
    key: 'paddingY',
    label: '垂直内边距(px)',
    type: 'number',
    min: 0,
    max: 30,
    step: 1,
    default: 2,
  },
  {
    key: 'borderRadius',
    label: '圆角(px)',
    type: 'number',
    min: 0,
    max: 50,
    step: 1,
    default: 10,
  },
  {
    key: 'borderWidth',
    label: '边框宽度(px)',
    type: 'number',
    min: 0,
    max: 5,
    step: 1,
    default: 0,
  },
  {
    key: 'borderColor',
    label: '边框颜色',
    type: 'color',
    default: 'transparent',
  },
  {
    key: 'boxShadow',
    label: '阴影',
    type: 'text',
    placeholder: 'none',
    default: 'none',
  },
  {
    key: 'slotFontSize',
    label: '内容字体大小(px)',
    type: 'number',
    min: 8,
    max: 100,
    step: 1,
    default: 14,
  },
  {
    key: 'slotColor',
    label: '内容颜色',
    type: 'color',
    default: '#303133',
  },
  {
    key: 'slotPadding',
    label: '内容内边距(px)',
    type: 'number',
    min: 0,
    max: 50,
    step: 1,
    default: 8,
  },
]

const dataSourceSchema: Field[] = [
  {
    key: 'enabled',
    label: '启用数据源',
    type: 'switch',
    default: false,
  },
  {
    key: 'url',
    label: 'API 地址',
    type: 'text',
    placeholder: 'http://localhost:3001/api/kpi',
    default: '',
  },
  {
    key: 'method',
    label: '请求方法',
    type: 'select',
    options: [
      { label: 'GET', value: 'GET' },
      { label: 'POST', value: 'POST' },
    ],
    default: 'GET',
  },
  {
    key: 'interval',
    label: '自动刷新(秒)',
    type: 'number',
    min: 0,
    max: 3600,
    step: 1,
    default: 0,
  },
  {
    key: 'dataPath',
    label: '数据根路径',
    type: 'text',
    placeholder: '例: data',
    default: '',
  },
  {
    key: 'valuePath',
    label: '数值路径',
    type: 'text',
    placeholder: '例: data.value 或 value',
    default: '',
  },
  {
    key: 'headers',
    label: '请求头(JSON)',
    type: 'text',
    placeholder: '{"Authorization": "Bearer token"}',
    default: '',
  },
]

const componentSchema: Field[] = [
  {
    key: 'value',
    label: '显示值',
    type: 'text',
    placeholder: '99',
    default: '0',
  },
  {
    key: 'type',
    label: '类型',
    type: 'select',
    options: [
      { label: '主要', value: 'primary' },
      { label: '成功', value: 'success' },
      { label: '警告', value: 'warning' },
      { label: '危险', value: 'danger' },
      { label: '信息', value: 'info' },
    ],
    default: 'primary',
  },
  {
    key: 'dot',
    label: '小圆点模式',
    type: 'switch',
    default: false,
  },
  {
    key: 'maxValue',
    label: '最大值',
    type: 'number',
    min: 1,
    max: 999,
    step: 1,
    default: 99,
  },
  {
    key: 'hidden',
    label: '隐藏徽章',
    type: 'switch',
    default: false,
  },
  {
    key: 'showZero',
    label: '显示0值',
    type: 'switch',
    default: false,
  },
  {
    key: 'offsetX',
    label: 'X偏移量',
    type: 'number',
    min: -100,
    max: 100,
    step: 1,
    default: 0,
  },
  {
    key: 'offsetY',
    label: 'Y偏移量',
    type: 'number',
    min: -100,
    max: 100,
    step: 1,
    default: 0,
  },
  {
    key: 'showSlot',
    label: '显示插槽内容',
    type: 'switch',
    default: true,
  },
  {
    key: 'slotText',
    label: '插槽文本',
    type: 'text',
    placeholder: '内容',
    default: '内容',
  },
]

registerSchema({
  types: ['badge'],
  styleSchema,
  dataSourceSchema,
  componentSchema,
})
