/**
 * LineChart 折线图组件属性配置
 */
import { registerSchema, type Field } from '@/components/siderBar/properties/schema/types'

const dataSourceSchema: Field[] = [
  {
    key: 'enabled',
    label: '启用数据源',
    type: 'switch',
    default: false,
  },
  {
    key: 'url',
    label: 'API 地址',
    type: 'text',
    placeholder: 'http://localhost:3001/api/chart/nested',
    default: '',
  },
  {
    key: 'method',
    label: '请求方法',
    type: 'select',
    options: [
      { label: 'GET', value: 'GET' },
      { label: 'POST', value: 'POST' },
    ],
    default: 'GET',
  },
  {
    key: 'interval',
    label: '自动刷新(秒)',
    type: 'number',
    min: 0,
    max: 3600,
    step: 1,
    default: 0,
  },
  {
    key: 'dataPath',
    label: '数据值路径',
    type: 'text',
    placeholder: '例: data.chart.values 或 readings.temperatures',
    default: '',
  },
  {
    key: 'xAxisPath',
    label: 'X轴标签路径',
    type: 'text',
    placeholder: '例: data.chart.categories 或 readings.timestamps',
    default: '',
  },
  {
    key: 'seriesNamePath',
    label: '系列名称路径',
    type: 'text',
    placeholder: '例: data.seriesName (可选)',
    default: '',
  },
  {
    key: 'headers',
    label: '请求头(JSON)',
    type: 'text',
    placeholder: '{"Authorization": "Bearer token"}',
    default: '',
  },
]

const componentSchema: Field[] = [
  {
    key: 'option',
    label: '完整 ECharts Option (JSON) - 高级配置会覆盖下方简单配置',
    type: 'text',
    placeholder: '{ "tooltip": {...}, "series": [...] }',
  },
  {
    key: 'title',
    label: '图表标题',
    type: 'text',
    placeholder: '折线图',
    default: '',
  },
  {
    key: 'seriesName',
    label: '系列名称',
    type: 'text',
    placeholder: 'Series',
    default: 'Series',
  },
  {
    key: 'dataInput',
    label: '数据 (逗号分隔)',
    type: 'text',
    placeholder: '150, 230, 224, 218, 135, 147, 260',
    default: '150, 230, 224, 218, 135, 147, 260',
  },
  {
    key: 'xAxisInput',
    label: 'X 轴标签 (逗号分隔)',
    type: 'text',
    placeholder: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun',
    default: 'Mon, Tue, Wed, Thu, Fri, Sat, Sun',
  },
  {
    key: 'lineColor',
    label: '线条颜色',
    type: 'color',
    default: '#5470c6',
  },
  {
    key: 'lineWidth',
    label: '线条宽度',
    type: 'number',
    min: 1,
    max: 10,
    step: 1,
    default: 2,
  },
  {
    key: 'smooth',
    label: '平滑曲线',
    type: 'switch',
    default: true,
  },
  {
    key: 'showArea',
    label: '显示区域',
    type: 'switch',
    default: false,
  },
  {
    key: 'areaOpacity',
    label: '区域透明度',
    type: 'number',
    min: 0,
    max: 1,
    step: 0.1,
    default: 0.3,
  },
  {
    key: 'showSymbol',
    label: '显示数据点',
    type: 'switch',
    default: true,
  },
  {
    key: 'symbolSize',
    label: '数据点大小',
    type: 'number',
    min: 0,
    max: 20,
    step: 1,
    default: 6,
  },
  {
    key: 'lineType',
    label: '线条类型',
    type: 'select',
    options: [
      { label: '实线', value: 'solid' },
      { label: '虚线', value: 'dashed' },
      { label: '点线', value: 'dotted' },
    ],
    default: 'solid',
  },
  {
    key: 'showLegend',
    label: '显示图例',
    type: 'switch',
    default: true,
  },
  {
    key: 'legendPosition',
    label: '图例位置',
    type: 'select',
    options: [
      { label: '顶部', value: 'top' },
      { label: '底部', value: 'bottom' },
      { label: '左侧', value: 'left' },
      { label: '右侧', value: 'right' },
    ],
    default: 'top',
  },
  {
    key: 'showTooltip',
    label: '显示提示框',
    type: 'switch',
    default: true,
  },
  {
    key: 'xAxisName',
    label: 'X 轴名称',
    type: 'text',
    placeholder: '时间',
    default: '',
  },
  {
    key: 'yAxisName',
    label: 'Y 轴名称',
    type: 'text',
    placeholder: '数值',
    default: '',
  },
  {
    key: 'showXAxisLine',
    label: '显示 X 轴线',
    type: 'switch',
    default: true,
  },
  {
    key: 'showYAxisLine',
    label: '显示 Y 轴线',
    type: 'switch',
    default: true,
  },
  {
    key: 'showXAxisLabel',
    label: '显示 X 轴标签',
    type: 'switch',
    default: true,
  },
  {
    key: 'showYAxisLabel',
    label: '显示 Y 轴标签',
    type: 'switch',
    default: true,
  },
  {
    key: 'showGrid',
    label: '显示网格线',
    type: 'switch',
    default: true,
  },
]

registerSchema({
  types: ['lineChart'],
  dataSourceSchema,
  componentSchema,
})
