/**
 * GaugeChart 仪表盘组件属性配置
 */
import { registerSchema, type Field } from '@lowcode/editor/components/siderBar/properties/schema/types'

const dataSourceSchema: Field[] = [
  {
    key: 'enabled',
    label: '启用数据源',
    type: 'switch',
    default: false,
  },
  {
    key: 'url',
    label: 'API 地址',
    type: 'text',
    placeholder: 'http://localhost:3001/api/gauge',
    default: '',
  },
  {
    key: 'method',
    label: '请求方法',
    type: 'select',
    options: [
      { label: 'GET', value: 'GET' },
      { label: 'POST', value: 'POST' },
    ],
    default: 'GET',
  },
  {
    key: 'interval',
    label: '自动刷新(秒)',
    type: 'number',
    min: 0,
    max: 3600,
    step: 1,
    default: 0,
  },
  {
    key: 'dataPath',
    label: '数据路径',
    type: 'text',
    placeholder: '例: data.value',
    default: '',
  },
  {
    key: 'headers',
    label: '请求头(JSON)',
    type: 'text',
    placeholder: '{"Authorization": "Bearer token"}',
    default: '',
  },
]

const componentSchema: Field[] = [
  {
    key: 'title',
    label: '图表标题',
    type: 'text',
    default: '',
  },
  {
    key: 'value',
    label: '数值',
    type: 'number',
    min: 0,
    max: 100,
    default: 75,
  },
  {
    key: 'name',
    label: '名称',
    type: 'text',
    default: 'Progress',
  },
  {
    key: 'min',
    label: '最小值',
    type: 'number',
    default: 0,
  },
  {
    key: 'max',
    label: '最大值',
    type: 'number',
    default: 100,
  },
  {
    key: 'startAngle',
    label: '起始角度',
    type: 'number',
    min: 0,
    max: 360,
    default: 225,
  },
  {
    key: 'endAngle',
    label: '结束角度',
    type: 'number',
    min: -360,
    max: 360,
    default: -45,
  },
  {
    key: 'splitNumber',
    label: '分割段数',
    type: 'number',
    min: 1,
    max: 20,
    default: 10,
  },
  {
    key: 'showProgress',
    label: '显示进度条',
    type: 'switch',
    default: true,
  },
  {
    key: 'progressWidth',
    label: '进度条宽度',
    type: 'number',
    min: 1,
    max: 50,
    default: 10,
  },
  {
    key: 'axisLineWidth',
    label: '轴线宽度',
    type: 'number',
    min: 1,
    max: 50,
    default: 10,
  },
  {
    key: 'pointerColor',
    label: '指针颜色',
    type: 'text',
    default: 'auto',
  },
  {
    key: 'pointerLength',
    label: '指针长度',
    type: 'text',
    default: '70%',
  },
  {
    key: 'pointerWidth',
    label: '指针宽度',
    type: 'number',
    min: 1,
    max: 20,
    default: 8,
  },
  {
    key: 'showAxisTick',
    label: '显示刻度',
    type: 'switch',
    default: true,
  },
  {
    key: 'axisTickSplitNumber',
    label: '刻度分割',
    type: 'number',
    min: 1,
    max: 10,
    default: 5,
  },
  {
    key: 'showSplitLine',
    label: '显示分隔线',
    type: 'switch',
    default: true,
  },
  {
    key: 'splitLineLength',
    label: '分隔线长度',
    type: 'number',
    min: 1,
    max: 50,
    default: 15,
  },
  {
    key: 'showAxisLabel',
    label: '显示轴标签',
    type: 'switch',
    default: true,
  },
  {
    key: 'axisLabelDistance',
    label: '轴标签距离',
    type: 'number',
    min: 0,
    max: 100,
    default: 25,
  },
  {
    key: 'axisLabelFontSize',
    label: '轴标签字号',
    type: 'number',
    min: 8,
    max: 24,
    default: 12,
  },
  {
    key: 'detailFormatter',
    label: '详情格式',
    type: 'text',
    default: '{value}',
  },
  {
    key: 'detailFontSize',
    label: '详情字号',
    type: 'number',
    min: 8,
    max: 48,
    default: 20,
  },
  {
    key: 'detailOffsetX',
    label: '详情水平偏移',
    type: 'text',
    default: '0%',
  },
  {
    key: 'detailOffsetY',
    label: '详情垂直偏移',
    type: 'text',
    default: '70%',
  },
]

registerSchema({
  types: ['gaugeChart'],
  dataSourceSchema,
  componentSchema,
})
